### ISSUE TITLE
[iOS] survey cannot show normally in survey wall

### ISSUE THREAD

**Issue by mailtime-wing** [inbrainai/react-native#14]
The survey cannot show normally in suvery wall ```inbrain.showSurveys()```.
There is a pressable empty box instead. Please see below image.

![Image from iOS](https://user-images.githubusercontent.com/58675852/130222713-e066062e-1b62-465c-b41e-d34c7a1840be.png)

**Comment by zohrus** [comment]
Apologies for the delay. Problem should be solved by now. Please re-open if not.
